packages:
  - packages/*
  - tests/*
  - website

catalog:
  '@biomejs/biome': ^2.4.4
  '@dipakparmar/docusaurus-plugin-umami': ^2.4.0
  '@docusaurus/core': ^3.9.2
  '@docusaurus/faster': ^3.9.2
  '@docusaurus/module-type-aliases': ^3.9.2
  '@docusaurus/preset-classic': ^3.9.2
  '@docusaurus/theme-mermaid': ^3.9.2
  '@docusaurus/tsconfig': ^3.9.2
  '@docusaurus/types': ^3.9.2
  '@electron-forge/cli': ^7.11.1
  '@electron-forge/plugin-vite': ^7.11.1
  '@enkaku/codec': ^0.12.0
  '@hono/node-server': ^1.19.9
  '@logtape/logtape': ^2.0.2
  '@napi-rs/keyring': ^1.2.0
  '@noble/ciphers': ^2.1.1
  '@noble/curves': ^2.0.1
  '@noble/hashes': ^2.0.0
  '@orama/plugin-docusaurus-v3': ^3.1.18
  '@playwright/test': 1.58.2
  '@scure/base': ^2.0.0
  '@standard-schema/spec': ^1.1.0
  '@swc/cli': ^0.8.0
  '@swc/core': ^1.15.17
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@types/node': 25.3.2
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': ^4.2.3
  '@vitest/ui': ^4.0.18
  ajv: ^8.18.0
  ajv-formats: ^3.0.1
  canonicalize: 2.1.0
  del-cli: ^7.0.0
  electron: ^40.6.1
  electron-store: ^11.0.2
  emittery: ^1.2.1
  expo: ~54.0.8
  expo-crypto: ^55.0.8
  expo-secure-store: ^55.0.8
  expo-status-bar: ~55.0.4
  get-port: ^7.1.0
  happy-dom: ^20.7.0
  json-schema-to-ts: ^3.1.1
  playwright: ^1.55.0
  react: 19.2.0
  react-dom: 19.2.0
  react-native: 0.83.2
  react-native-electron: ^0.22.1
  react-native-web: 0.21.2
  tsx: ^4.21.0
  turbo: ^2.8.11
  typedoc: ^0.28.17
  typedoc-plugin-markdown: ^4.10.0
  typescript: 5.9.2
  uint8arrays: ^5.1.0
  undici: ^7.22.0
  vite: ^7.3.1
  vitest: ^4.0.18

catalogMode: prefer

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - unrs-resolver
