packages:
  - packages/*
  - tests/*
  - website

catalog:
  '@biomejs/biome': ^2.2.4
  '@docusaurus/core': ^3.9.1
  '@docusaurus/faster': ^3.9.1
  '@docusaurus/module-type-aliases': ^3.9.1
  '@docusaurus/preset-classic': ^3.9.1
  '@docusaurus/theme-mermaid': ^3.9.1
  '@docusaurus/tsconfig': ^3.9.1
  '@docusaurus/types': ^3.9.1
  '@electron-forge/cli': ^7.9.0
  '@electron-forge/plugin-vite': ^7.9.0
  '@hono/node-server': ^1.19.4
  '@jest/globals': ^30.1.2
  '@napi-rs/keyring': ^1.2.0
  '@noble/curves': ^2.0.1
  '@noble/hashes': ^2.0.0
  '@orama/plugin-docusaurus-v3': ^3.1.14
  '@playwright/test': 1.55.1
  '@scure/base': ^2.0.0
  '@standard-schema/spec': ^1.0.0
  '@swc/cli': ^0.7.8
  '@swc/core': ^1.13.19
  '@swc/jest': ^0.2.39
  '@types/jest': ^30.0.0
  '@types/node': 24.5.2
  '@types/react': ^19.1.14
  '@vitejs/plugin-react-swc': ^4.1.0
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  canonicalize: 2.1.0
  del-cli: ^7.0.0
  electron: ^38.1.2
  electron-store: ^10.1.0
  emittery: ^1.2.0
  expo: ~54.0.8
  expo-crypto: ^15.0.7
  expo-secure-store: ^15.0.7
  get-port: ^7.1.0
  jest: ^30.1.3
  json-schema-to-ts: ^3.1.1
  playwright: ^1.55.0
  react: 19.1.1
  react-dom: 19.1.0
  react-native-electron: ^0.22.0
  react-native-web: 0.21.1
  tsx: ^4.20.6
  turbo: ^2.5.8
  typedoc: ^0.28.13
  typedoc-plugin-markdown: ^4.9.0
  typescript: ~5.9.2
  uint8arrays: ^5.1.0
  undici: ^7.16.0
  vite: ^7.1.7

catalogMode: prefer

catalogs:
  expo:
    expo: ~54.0.10
    expo-status-bar: ~3.0.8
    react: 19.1.1
    react-native: 0.81.4

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - unrs-resolver
