packages:
  - packages/*
  - tests/*
  - website

catalog:
  '@biomejs/biome': ^2.2.4
  '@hono/node-server': ^1.19.2
  '@jest/globals': ^30.1.2
  '@napi-rs/keyring': ^1.2.0
  '@noble/curves': ^2.0.0
  '@noble/hashes': ^2.0.0
  '@scure/base': ^2.0.0
  '@standard-schema/spec': ^1.0.0
  '@swc/cli': ^0.7.8
  '@swc/core': ^1.13.5
  '@swc/jest': ^0.2.39
  '@types/jest': ^30.0.0
  '@types/node': ^24.4.0
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  canonicalize: 2.1.0
  del-cli: ^6.0.0
  emittery: ^1.2.0
  expo-crypto: ^15.0.7
  expo-secure-store: ^15.0.7
  get-port: ^7.1.0
  jest: ^30.1.3
  json-schema-to-ts: ^3.1.1
  tsx: ^4.20.5
  turbo: ^2.5.6
  typedoc: ^0.28.13
  typedoc-plugin-markdown: ^4.8.1
  uint8arrays: ^5.1.0
  undici: ^7.16.0

catalogMode: manual

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - unrs-resolver
