packages:
  - packages/*
  - tests/*
  - website

catalog:
  '@biomejs/biome': ^2.1.2
  '@hono/node-server': ^1.17.0
  '@jest/globals': ^30.0.4
  '@napi-rs/keyring': ^1.1.8
  '@noble/curves': ^1.9.4
  '@noble/hashes': ^1.8.0
  '@scure/base': ^1.2.6
  '@standard-schema/spec': ^1.0.0
  '@swc/cli': ^0.7.8
  '@swc/core': ^1.13.0
  '@swc/jest': ^0.2.39
  '@types/jest': ^30.0.0
  '@types/node': ^24.0.15
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  canonicalize: ^2.1.0
  del-cli: ^6.0.0
  emittery: ^1.2.0
  expo-crypto: ^14.1.5
  expo-secure-store: ^14.2.3
  get-port: ^7.1.0
  jest: ^30.0.4
  json-schema-to-ts: ^3.1.1
  tsx: ^4.20.3
  turbo: ^2.5.5
  typedoc: ^0.28.7
  typedoc-plugin-markdown: ^4.7.0
  uint8arrays: ^5.1.0
  undici: ^7.12.0

catalogMode: manual

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - unrs-resolver
