packages:
  - packages/*
  - tests/*
  - website

catalog:
  '@biomejs/biome': ^2.3.4
  '@docusaurus/core': ^3.9.2
  '@docusaurus/faster': ^3.9.2
  '@docusaurus/module-type-aliases': ^3.9.2
  '@docusaurus/preset-classic': ^3.9.2
  '@docusaurus/theme-mermaid': ^3.9.2
  '@docusaurus/tsconfig': ^3.9.2
  '@docusaurus/types': ^3.9.2
  '@electron-forge/cli': ^7.10.2
  '@electron-forge/plugin-vite': ^7.10.2
  '@hono/node-server': ^1.19.6
  '@jest/globals': ^30.2.0
  '@napi-rs/keyring': ^1.2.0
  '@noble/curves': ^2.0.1
  '@noble/hashes': ^2.0.0
  '@orama/plugin-docusaurus-v3': ^3.1.16
  '@playwright/test': 1.56.1
  '@scure/base': ^2.0.0
  '@standard-schema/spec': ^1.0.0
  '@swc/cli': ^0.7.9
  '@swc/core': ^1.15.0
  '@swc/jest': ^0.2.39
  '@testing-library/jest-dom': ^6.9.1
  '@types/jest': ^30.0.0
  '@types/node': 24.10.0
  '@types/react': ^19.1.14
  '@vitejs/plugin-react-swc': ^4.2.1
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  canonicalize: 2.1.0
  del-cli: ^7.0.0
  electron: ^39.1.0
  electron-store: ^11.0.2
  emittery: ^1.2.0
  expo: ~54.0.8
  expo-crypto: ^15.0.7
  expo-secure-store: ^15.0.7
  get-port: ^7.1.0
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  json-schema-to-ts: ^3.1.1
  playwright: ^1.55.0
  react: 19.1.0
  react-dom: 19.1.0
  react-native-electron: ^0.22.0
  react-native-web: 0.21.1
  tsx: ^4.20.6
  turbo: ^2.6.0
  typedoc: ^0.28.14
  typedoc-plugin-markdown: ^4.9.0
  typescript: ~5.9.2
  uint8arrays: ^5.1.0
  undici: ^7.16.0
  vite: ^7.2.0

catalogMode: prefer

catalogs:
  expo:
    expo: ~54.0.22
    expo-status-bar: ~3.0.8
    react: 19.1.0
    react-native: 0.81.5

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - unrs-resolver
