packages:
  - packages/*
  - tests/*
  - website

catalog:
  '@biomejs/biome': ^2.3.11
  '@dipakparmar/docusaurus-plugin-umami': ^2.4.0
  '@docusaurus/core': ^3.9.2
  '@docusaurus/faster': ^3.9.2
  '@docusaurus/module-type-aliases': ^3.9.2
  '@docusaurus/preset-classic': ^3.9.2
  '@docusaurus/theme-mermaid': ^3.9.2
  '@docusaurus/tsconfig': ^3.9.2
  '@docusaurus/types': ^3.9.2
  '@electron-forge/cli': ^7.11.1
  '@electron-forge/plugin-vite': ^7.11.1
  '@hono/node-server': ^1.19.9
  '@logtape/logtape': ^2.0.0
  '@napi-rs/keyring': ^1.2.0
  '@noble/curves': ^2.0.1
  '@noble/hashes': ^2.0.0
  '@orama/plugin-docusaurus-v3': ^3.1.18
  '@playwright/test': 1.57.0
  '@scure/base': ^2.0.0
  '@standard-schema/spec': ^1.1.0
  '@swc/cli': ^0.7.10
  '@swc/core': ^1.15.8
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@types/node': 25.0.9
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/ui': ^4.0.17
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  canonicalize: 2.1.0
  del-cli: ^7.0.0
  electron: ^40.0.0
  electron-store: ^11.0.2
  emittery: ^1.2.0
  expo: ~54.0.8
  expo-crypto: ^15.0.8
  expo-secure-store: ^15.0.8
  get-port: ^7.1.0
  happy-dom: ^20.3.1
  json-schema-to-ts: ^3.1.1
  playwright: ^1.55.0
  react: 19.1.0
  react-dom: 19.1.0
  react-native-electron: ^0.22.1
  react-native-web: 0.21.2
  tsx: ^4.21.0
  turbo: ^2.7.4
  typedoc: ^0.28.16
  typedoc-plugin-markdown: ^4.9.0
  typescript: 5.9.2
  uint8arrays: ^5.1.0
  undici: ^7.18.2
  vite: ^7.3.1
  vitest: ^4.0.17

catalogMode: prefer

catalogs:
  expo:
    '@types/react': ~19.2.8
    expo: ~54.0.30
    expo-status-bar: ~3.0.9
    react: 19.1.0
    react-native: 0.81.5

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - unrs-resolver
