packages:
  - packages/*
  - tests/*
  - website

catalogMode: strict
catalog:
  "@biomejs/biome": ^1.9.4
  "@dipakparmar/docusaurus-plugin-umami": ^2.3.0
  "@docusaurus/core": ^3.8.1
  "@docusaurus/faster": ^3.8.1
  "@docusaurus/module-type-aliases": ^3.8.1
  "@docusaurus/preset-classic": ^3.8.1
  "@docusaurus/theme-mermaid": ^3.8.1
  "@docusaurus/tsconfig": ^3.8.1
  "@docusaurus/types": ^3.8.1
  "@hono/node-server": ^1.14.4
  "@jest/globals": ^30.0.0
  "@mdx-js/react": ^3.0.0
  "@napi-rs/keyring": ^1.1.8
  "@noble/curves": ^1.9.2
  "@noble/hashes": ^1.8.0
  "@orama/plugin-docusaurus-v3": ^3.1.7
  "@scure/base": ^1.2.6
  "@standard-schema/spec": ^1.0.0
  "@swc/cli": ^0.7.7
  "@swc/core": ^1.12.0
  "@swc/jest": ^0.2.38
  "@types/jest": ^29.5.14
  "@types/node": ^24.0.0
  "@types/react": ^19.1.7
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  canonicalize: ^2.1.0
  clsx: ^2.0.0
  del-cli: ^6.0.0
  docusaurus-plugin-typedoc: ^1.4.0
  emittery: ^1.1.0
  expo-crypto: ^14.1.5
  expo-secure-store: ^14.2.3
  get-port: ^7.1.0
  jest: ^30.0.0
  json-schema-to-ts: ^3.1.1
  prism-react-renderer: ^2.4.1
  react: ^19.1.0
  react-dom: ^19.1.0
  tsx: ^4.20.1
  turbo: ^2.5.4
  typedoc: ^0.28.5
  typedoc-plugin-markdown: ^4.6.4
  uint8arrays: ^5.1.0
  undici: ^7.10.0
