name: Setup mobile environment
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      id: pnpm-install
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build packages
      shell: bash
      run: pnpm run build:ci

    - name: Install Maestro
      shell: bash
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        echo "$HOME/.maestro/bin" >> $GITHUB_PATH
